### DISCUSSION TITLE
Looking for a best way to take backup of the bookmarks incase if my VPS got deleted

### DISCUSSION THREAD

**Discussion by KunalScriptz** [goniszewski/grimoire#135] [Q&A]
Hi, whats the most preferrable way of backing uo?

**Comment by goniszewski** [comment]
Hello @thecodingwizardx! A good question.

The [ability to export bookmarks](https://github.com/users/goniszewski/projects/1/views/1?pane=issue&itemId=46191243) is currently in the backlog. But even without it, there's still some room to implement your own backup mechanism as, by default, the Grimoire stores all its data in a single directory (DB + images). Let me give you some propositions:
- Automate your backup using *Restic*: a battle-tested solution I'm using myself (with BackBlaze B2 storage, but there's many more to choose from). [[GitHub]](https://github.com/restic/restic) [[Guide for AWS S3]](https://restic.readthedocs.io/en/latest/080_examples.html#setting-up-restic-with-amazon-s3)
- Attach backup sidekick container with *docker-volume-backup*: powerful and easy to deploy automatic backups. [[GitHub]](https://github.com/offen/docker-volume-backup) [[Examples]](https://offen.github.io/docker-volume-backup/recipes/)
- Use Docker's in-build backup tool: with a single command, that you can use with e.g. *cron* to schedule it, you could use a shell command like `docker run --rm -v grimoire_data:/volume -v $(pwd):/backup alpine tar -czvf /backup/grimoire_backup.tar.gz -C /volume ./` to create a single backup file.

I'll create a note for myself to write down some actual guide on how to do this for [Grimoire's docs](https://grimoire.pro/docs/). Please don't hesitate to share your findings on this topic as it may benefit us all :)

PS I will move this to discussions.

**Comment by eleblebici** [comment]
Hello,

Expanding the last proposition that @goniszewski shared. I tried to backup and restore the data and wanted to share the exact commands that I used.

As mentioned, you can create a single backup file with the following command. But you first need to check what volume that the grimoire container is using. 

`sudo docker inspect grimoire --format '{{ json .Mounts }}' | jq`

It will give an output like:

```
[
  {
    "Type": "volume",
    "Name": "grimoire_grimoire_data",
    "Source": "/var/snap/docker/common/var-lib-docker/volumes/grimoire_grimoire_data/_data",
    "Destination": "/app/data",
    "Driver": "local",
    "Mode": "z",
    "RW": true,
    "Propagation": ""
  }
]
```

As the name is "grimoire_grimoire_data" in my setup, I'm changing the command to:

`docker run --rm -v grimoire_grimoire_data:/volume -v $(pwd):/backup alpine tar -czvf /backup/grimoire_backup.tar.gz -C /volume ./`

It will generate the "grimoire_backup.tar.gz" file in the directory you are in.

Copy that file to the machine that you want to restore grimoire backup. Then create a new volume with that data:

`docker run --rm   -v mydata:/data   -v $(pwd):/backup   alpine   sh -c "cd /data && tar -xzvf /backup/grimoire_backup.tar.gz"`

Then you can run grimoire with `docker compose up -d` by using the following `docker-compose.yml `file:

```
services:
  grimoire:
    image: goniszewski/grimoire:latest # or change from 'latest' to 'preview' to use the latest preview version
    container_name: grimoire
    restart: unless-stopped
    environment:
      - PORT=5173
      - PUBLIC_HTTPS_ONLY=false
      - PUBLIC_SIGNUP_DISABLED=false
    volumes:
      - mydata:/app/data/
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:$PORT/api/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - '${PORT:-5173}:${PORT:-5173}'
volumes:
  mydata:
    external: true
```
