### ISSUE TITLE
SQLiteError: no such table: user

### ISSUE THREAD

**Issue by tehniemer** [goniszewski/grimoire#133]
Followed the docker install instructions and was presented with the following error when trying to access the service.

```
SQLiteError: no such table: user

1
      at prepare (bun:sqlite:280:10)
      at prepareQuery (/app/node_modules/drizzle-orm/bun-sqlite/session.js:20:30)
      at _prepare (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:572:73)
      at all (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:588:17)
      at execute (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:596:19)
      at then (/app/node_modules/drizzle-orm/query-promise.js:21:17)
15 |   logger;
16 |   exec(query) {
17 |     this.client.exec(query);
18 |   }
19 |   prepareQuery(query, fields, executeMethod, isResponseInArrayMode, customResultMapper) {
20 |     const stmt = this.client.prepare(query.sql);
```

Here's my compose snippet

```
services:
  grimoire:
    image: goniszewski/grimoire:develop
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grimoire
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - $GRIMOIRE_PORT:5173
    security_opt:
      - no-new-privileges=true
    logging:
      options:
        max-size: 2m
        max-file: "3"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/grimoire:/app/data/
    environment:
      - PORT=5173
      - PUBLIC_HTTPS_ONLY=false
      - PUBLIC_SIGNUP_DISABLED=false
    labels:
      - homepage.group=Containers
      - homepage.name=Grimoire
      - homepage.icon=grimoire
      - homepage.description=Bookmark Management
      - homepage.href=https://grimoire.$DOMAINNAME
      - homepage.siteMonitor=http://$HOST:$GRIMOIRE_PORT
      - traefik.enable=true
      - traefik.http.routers.grimoire-rtr.entrypoints=https
      - traefik.http.routers.grimoire-rtr.rule=Host(`grimoire.$DOMAINNAME`)
      - traefik.http.routers.grimoire-rtr.middlewares=chain-no-auth@file # No Authentication
      - traefik.http.routers.grimoire-rtr.service=grimoire-svc
      - traefik.http.services.grimoire-svc.loadbalancer.server.port=5173
```
