### ISSUE TITLE
Cannot access Ollama, "ERR_NAME_NOT_RESOLVED"

### ISSUE THREAD

**Issue by ctrenthem159** [goniszewski/grimoire#138]
I'm using Grimoire, Ollama, and OpenWebUI in a single Docker Compose file, and while Openwebui can communicate with Ollama, Grimoire cannot.

Docker compose file:
```
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    networks: ['ollama']
    volumes:
      - ollama-root:/root/.ollama

  grimoire:
    image: goniszewski/grimoire:latest
    container_name: grimoire
    restart: unless-stopped
    networks: ['backend', 'ollama']
    environment:
      - PORT=5173
      - PUBLIC_HTTPS_ONLY=false
      - PUBLIC_ORIGIN=https://grimoire.DOMAIN
      - PUBLIC_SIGNUP_DISABLED=true
    volumes:
      - grimoire-data:/app/data

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    networks: ['backend', 'ollama']
    environment:
      - WEBUI_URL=https://ollama.DOMAIN
    volumes:
      - ollama-data:/app/backend/data

(associated top-level volumes and networks items here)
```

openwebui works:
![image](https://github.com/user-attachments/assets/a4da4cef-3259-43aa-aca1-638b36109d86)

![image](https://github.com/user-attachments/assets/89de2f8a-ce72-438c-b408-5cfe1f03b944)

but Grimoire does not:
![image](https://github.com/user-attachments/assets/f9492725-ad0e-452a-ac2a-48e4e603c046)

If I try to access ollama from the host using the container name, I get this result
```
18:50:36 chris >> curl http://ollama:11434/api/tags
curl: (6) Could not resolve host: ollama
```

but when accessing it using it's IP (according to `docker network inspect ollama`)
```
18:50:31 chris >> curl 172.18.0.2:11434/api/tags
{"models":[{"name":"llama3.2:1b","model":"llama3.2:1b","modified_at":"2024-09-30T17:44:17.913431968Z","size":1321098329,"digest":"baf6a787fdffd633537aa2eb51cfd54cb93ff08e28040095462bb63daf552878","details":{"parent_model":"","format":"gguf","family":"llama","families":["llama"],"parameter_size":"1.2B","quantization_level":"Q8_0"}}]}%
```

Grimoire and openwebui are behind a reverse proxy (NPM) with SSL enabled and other than not being able to access Ollama, everything else is working 100%.
