### ISSUE TITLE
The Extension is not working with the self-hosted intance: Getting error: Something went wrong, try again please.

### ISSUE THREAD

**Issue by AmoghSaxena** [goniszewski/grimoire#159]
![image](https://github.com/user-attachments/assets/41dd85b2-235e-4b78-90be-3f4c95c949d1)

Even after creating a non admin user I am not able to connect it from the extension.

This is my compose file.

```yaml
services:
  grimoire:
    image: goniszewski/grimoire:develop
    container_name: grimoire
    restart: unless-stopped
    environment:
      - PORT=5173
      - PUBLIC_HTTPS_ONLY=true
      - PUBLIC_SIGNUP_DISABLED=true
    volumes:
      - /workstation/bookmark/:/app/data/
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:$PORT/api/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - '5173:${PORT:-5173}'

#volumes:
#  grimoire_data:



```

Even though with the same user I am able to bookmark things manually from the website.

![image](https://github.com/user-attachments/assets/9a5a14bf-dc49-4b64-bd0a-6796519d1c99)
