### ISSUE TITLE
ConnectionRefused: Unable to connect. Is the computer able to access the url?  path: "<url>"

### ISSUE THREAD

**Issue by ndpm13** [goniszewski/grimoire#171]
**Describe the bug**
When I tried to add a new bookmark nothings happens and I get this error in the logs:
```
Fetching metadata for URL:  <url>

ConnectionRefused: Unable to connect. Is the computer able to access the url?
 path: "<url>"
```

**To Reproduce**
1. I used this docker-compose.yml:
```yml
services:
  grimoire:
    image: goniszewski/grimoire:main # this happens with latest as well
    container_name: grimoire
    restart: unless-stopped
    environment:
      - PORT=5173
      - PUBLIC_HTTPS_ONLY=false
      - PUBLIC_SIGNUP_DISABLED=false
    volumes:
      - grimoire_data:/app/data/
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:$PORT/api/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - '${PORT:-5173}:${PORT:-5173}'
volumes:
  grimoire_data:
```
2. Create an admin account
3. Add a new bookmark
4. See error in the logs
```
Fetching metadata for URL:  <url>

ConnectionRefused: Unable to connect. Is the computer able to access the url?
 path: "<url>"
```

**Expected behavior**
To not see the error ig? I literally can't add bookmarks

**Desktop:**
 - Device: Latitude E5450
 - OS: Void Linux
 - Browser: Brave
 - Version: Latest (I update my system regularly)  

**Host**
 - Device: Thinkpad L420
 - OS: Alpine Linux v3.21
 - Containerization Tools: Podman version 5.3.2

**Additional context**
I removed the build step from the compose file, but since the it ran find and I could log in to the web app I assumed it's not what's causing the issue.
