### ISSUE TITLE
Internal Error 500 after Installation

### ISSUE THREAD

**Issue by r00bit1984** [goniszewski/grimoire#182]
**Describe the bug**
After installing grimoire with docker compose on my server i can reach the WebUI but all it shows is 500 - Internal Error

**To Reproduce**

1. Use the provided docker-compose.yaml
2. `docker compose up -d`
3. Open the WebUI

**Expected behavior**
See the normal Grimoire WebUI

**Screenshots**

<img width="269" alt="Image" src="https://github.com/user-attachments/assets/af681035-a552-47d0-9e3b-94213cc4949c" />

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox, but also didnt work in safari
 - Version Firefox 136.0.4

**Additional context**
Logs from docker:
```
Configuration used {
  IS_DEV: false,
  ORIGIN: "http://localhost:5173",
  HTTPS_ONLY: false,
  SIGNUP_DISABLED: false,
}
Listening on 0.0.0.0:5173
15 |   logger;
16 |   exec(query) {
17 |     this.client.exec(query);
18 |   }
19 |   prepareQuery(query, fields, executeMethod, isResponseInArrayMode, customResultMapper) {
20 |     const stmt = this.client.prepare(query.sql);
                                  ^
SQLiteError: no such table: user
 errno: 1

      at prepare (bun:sqlite:280:10)
      at prepareQuery (/app/node_modules/drizzle-orm/bun-sqlite/session.js:20:30)
      at _prepare (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:572:73)
      at all (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:588:17)
      at execute (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:596:19)
      at then (/app/node_modules/drizzle-orm/query-promise.js:21:17)

15 |   logger;
16 |   exec(query) {
17 |     this.client.exec(query);
18 |   }
19 |   prepareQuery(query, fields, executeMethod, isResponseInArrayMode, customResultMapper) {
20 |     const stmt = this.client.prepare(query.sql);
                                  ^
SQLiteError: no such table: user
 errno: 1

      at prepare (bun:sqlite:280:10)
      at prepareQuery (/app/node_modules/drizzle-orm/bun-sqlite/session.js:20:30)
      at _prepare (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:572:73)
      at all (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:588:17)
      at execute (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:596:19)
      at then (/app/node_modules/drizzle-orm/query-promise.js:21:17)

15 |   logger;
16 |   exec(query) {
17 |     this.client.exec(query);
18 |   }
19 |   prepareQuery(query, fields, executeMethod, isResponseInArrayMode, customResultMapper) {
20 |     const stmt = this.client.prepare(query.sql);
                                  ^
SQLiteError: no such table: user
 errno: 1

      at prepare (bun:sqlite:280:10)
      at prepareQuery (/app/node_modules/drizzle-orm/bun-sqlite/session.js:20:30)
      at _prepare (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:572:73)
      at all (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:588:17)
      at execute (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:596:19)
      at then (/app/node_modules/drizzle-orm/query-promise.js:21:17)

15 |   logger;
16 |   exec(query) {
17 |     this.client.exec(query);
18 |   }
19 |   prepareQuery(query, fields, executeMethod, isResponseInArrayMode, customResultMapper) {
20 |     const stmt = this.client.prepare(query.sql);
                                  ^
SQLiteError: no such table: user
 errno: 1

      at prepare (bun:sqlite:280:10)
      at prepareQuery (/app/node_modules/drizzle-orm/bun-sqlite/session.js:20:30)
      at _prepare (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:572:73)
      at all (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:588:17)
      at execute (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:596:19)
      at then (/app/node_modules/drizzle-orm/query-promise.js:21:17)

15 |   logger;
16 |   exec(query) {
17 |     this.client.exec(query);
18 |   }
19 |   prepareQuery(query, fields, executeMethod, isResponseInArrayMode, customResultMapper) {
20 |     const stmt = this.client.prepare(query.sql);
                                  ^
SQLiteError: no such table: user
 errno: 1

      at prepare (bun:sqlite:280:10)
      at prepareQuery (/app/node_modules/drizzle-orm/bun-sqlite/session.js:20:30)
      at _prepare (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:572:73)
      at all (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:588:17)
      at execute (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:596:19)
      at then (/app/node_modules/drizzle-orm/query-promise.js:21:17)

15 |   logger;
16 |   exec(query) {
17 |     this.client.exec(query);
18 |   }
19 |   prepareQuery(query, fields, executeMethod, isResponseInArrayMode, customResultMapper) {
20 |     const stmt = this.client.prepare(query.sql);
                                  ^
SQLiteError: no such table: user
 errno: 1

      at prepare (bun:sqlite:280:10)
      at prepareQuery (/app/node_modules/drizzle-orm/bun-sqlite/session.js:20:30)
      at _prepare (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:572:73)
      at all (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:588:17)
      at execute (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:596:19)
      at then (/app/node_modules/drizzle-orm/query-promise.js:21:17)


```

**Comment by Gdetrane** [comment]
I experience the same bug when deploying grimoire in a k3s cluster, using a PVC with a StorageClass for the app's data (this creates a dynamically provisioned iSCSI LUN on TrueNAS Scale using a dedicated CSI driver, permissions seem ok inside the pod), a simple Service and Tailscale's Ingress, which is my typical stack.

The issue seems to be the same, inspecting the logs from the pod, SQLITE complains about the user table not being there when it expects one:

```
Configuration used {
  IS_DEV: false,
  ORIGIN: "http://localhost:5173",
  HTTPS_ONLY: false,
  SIGNUP_DISABLED: false,
}
Listening on 0.0.0.0:5173
15 |   logger;
16 |   exec(query) {
17 |     this.client.exec(query);
18 |   }
19 |   prepareQuery(query, fields, executeMethod, isResponseInArrayMode, customResultMapper) {
20 |     const stmt = this.client.prepare(query.sql);
                                  ^
SQLiteError: no such table: user
 errno: 1

      at prepare (bun:sqlite:280:10)
      at prepareQuery (/app/node_modules/drizzle-orm/bun-sqlite/session.js:20:30)
      at _prepare (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:572:73)
      at all (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:588:17)
      at execute (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:596:19)
      at then (/app/node_modules/drizzle-orm/query-promise.js:21:17)

15 |   logger;
16 |   exec(query) {
17 |     this.client.exec(query);
18 |   }
19 |   prepareQuery(query, fields, executeMethod, isResponseInArrayMode, customResultMapper) {
20 |     const stmt = this.client.prepare(query.sql);
                                  ^
SQLiteError: no such table: user
 errno: 1

      at prepare (bun:sqlite:280:10)
      at prepareQuery (/app/node_modules/drizzle-orm/bun-sqlite/session.js:20:30)
      at _prepare (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:572:73)
      at all (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:588:17)
      at execute (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:596:19)
      at then (/app/node_modules/drizzle-orm/query-promise.js:21:17)
```

All components are up and running with no error and the service is accessible as expected, but the server returns the above error, I'm not using the helm chart, but applying resources directly with kubectl, values put together from the docker-compose available on the docs.

Some extra info:

```yaml
# grimoire-pvc.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: grimoire
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grimoire-app-data-pvc
  namespace: grimoire
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hpe-storageclass # for iSCSI in TrueNAS
  resources:
    requests:
      storage: 2Gi # For Grimoire's config, database, etc
```

```yaml
# grimoire-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grimoire
  namespace: grimoire
  labels:
    app: grimoire
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grimoire
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grimoire
    spec:
      containers:
      - name: grimoire
        image: goniszewski/grimoire:develop
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "5173"
        - name: PUBLIC_HTTPS_ONLY
          value: "false"
        - name: PUBLIC_SIGNUP_DISABLED
          value: "false"
        - name: TZ
          value: "Europe/Prague"
        ports:
        - name: http
          containerPort: 5173
        volumeMounts:
        - name: appdata # Corresponds to the iSCSI PVC
          mountPath: /app/data
        readinessProbe:
          httpGet:
            path: /api/health # From the docker-compose healthcheck
            port: 5173
          initialDelaySeconds: 20
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5173
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      volumes:
      - name: appdata
        persistentVolumeClaim:
          claimName: grimoire-app-data-pvc # iSCSI PVC for /app/data
```

```yaml
# grimoire-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: grimoire-svc
  namespace: grimoire
  labels:
    app: grimoire
spec:
  type: ClusterIP
  selector:
    app: grimoire
  ports:
  - name: http
    port: 5173
    targetPort: 5173
```

Steps to reproduce:
```bash
kubectl apply -f grimoire-pvc.yaml
kubectl apply -f grimoire-deployment.yaml
kubectl apply -g grimoire-service.yaml
```

Wait for the service to be up and running and reachable from the ingress (tailscale's built-in ingress in my case), watch the pod's log, as soon as the server is accessed at the appropriate domain a 500 immediately shows up and the SQLite error shows in the log

**Comment by Gdetrane** [comment]
@r00bit1984 I inspected the container from a shell and I've seen there's a database migration script that the image we're using doesn't seem to do automatically, so I've found a workaround that works for me in Kubernetes, should be very similar in Docker/Podman, it's an init step at the container level, I just added the following in my deployment file:

 ```yaml
spec:
      initContainers:
      - name: init-db
        image: goniszewski/grimoire:develop
        command: ["bun", "run", "./src/lib/database/migrate"]
```

Maybe this should be done automatically by the image? The problem was a missing `user` table in the sqlite db, running this script (I just looked up the package.json real quick and the dir structure in general, then took a wild guess) with bun (which I'm not familiar with but looks like a js/ts runtime) creates that table (and several others), then once I access the server I'm welcomed by the Initialization Wizard.

I'm not an expert with all the stuff used, including Kubernetes and containers in general, so I can't say whether this is a bug or just a misconfiguration on our side.

I figured I'd add to the conversation and hopefully offer something that would help you out, while I'm hoping  @goniszewski can jump in and evaluate the situation and maybe offer some insights.

I hope this is helpful!
