### ISSUE TITLE
Could not connect to Pocketbase

### ISSUE THREAD

**Issue by darrylgibbs** [goniszewski/grimoire#75]
**Describe the bug**
I've used the `docker-compose.yml` and `.env` files as stock from Github, and modified to my own spec, but regardless every time I login to the app's WebUI, I get the error **"Could not connect to Pocketbase on . Is it running? "** According to docker logs, both the grimoire and pocketbase containers are running fine.  Since Pocketbase can't connect, I can't move on to create a new user.  I've tried manually adding the `pb_data` and `pb_migrations` folders, and left them to be created by docker when running docker compose up, but neither method resolves the issue.

**To Reproduce**
Just use the default .env and docker-compose.yml

**Expected behavior**
To function as advertised.

**Screenshots**
![Screenshot 2024-03-29 214558](https://github.com/goniszewski/grimoire/assets/9167471/81fd2b1e-3e1f-4438-bade-7ba4699edbfa)

**Comment by darrylgibbs** [comment]
Sorry, I forgot to add in the original post, I found an issue from 2 days ago (https://github.com/goniszewski/grimoire/issues/70) but although @goniszewski seemed to imply the issue was fixed, it seems not to be, at least for me.

Or am I doing something wrong here?

**Comment by goniszewski** [comment]
Hello @darrylgibbs! Did you clone the repo, or are you just using the Compose and `.env` files?
`pb_migrations` needs to be available during the initial setup of the app.

**Comment by darrylgibbs** [comment]
Ah right, I had just recreated the `.env` and `docker-compose.yml` and manually made the folders.  I could have sworn I read that.

However, I just cloned the repo and followed the getting started docs to the letter, and still have the same result.  I noticed that the `.env`from the repo is slightly different from the one demonstrated in the docs.  The docs version has no value for `PUBLIC_POCKETBASE_URL=`. I tried both versions and still no luck.  I did manually change the Admin user info though.

**Comment by rogocal** [comment]
hi, i'm also having the same problem, i noticed i can get to the pocketbase api (using wget from inside the grimoire container), and I can login and everything kind of works, but the `cant connect` message keeps appearing, and if I go to the admin panel and try to see the pocketbase settings, the URL is not the same as my .env file.
IE:
```env
PUBLIC_POCKETBASE_URL=http://pocketbase:80
```
(you can add this as an example to work with internal docker networks)
Then from inside the app:
![image](https://github.com/goniszewski/grimoire/assets/11458421/3f7c0521-fa96-4285-9f3e-5ed2639d5af9)

**Comment by goniszewski** [comment]
@darrylgibbs strange indeed. Would you mind providing me with the steps you made to run the app (unsuccessfully)? Your `.env` content, stripped from sensitive information, would also be great to help me resolve this problem with you!

@rogocal the problem you described, a notification about connection problem, is clearly my oversight. The client-side code is trying to reach the PB instance over Docker's internal network, but it's outside it. The server part doesn't have this issue, so the rest of the app is working as it should be.

I do have a solution for the above problem, but I need to make additional tests for it. Here's the code that should ship with the next version: https://github.com/goniszewski/grimoire/pull/74

**Comment by darrylgibbs** [comment]
@goniszewski sure, no problem!!  I effectively I followed the docs, but I'll detail them and hopefully you'll spot something useful.

1. Cloned the entire git repo as per documentation to my Ubuntu 22.04 server.
2. I created the below `.env` file config.
3. I created the below `docker-compose.yml` config (I added my necessary networking settings, but I did also try the standard `docker-compose.yml` that came in the git repo.
4. I manually created the `pb_data` directory in the same directory as the git repo.  It has the same permissions as the rest of the repo (my user).
5. I ran `docker compose up -d` and checked in portainer that all the logs are healthy, and they were.  No complaints from the containers.

.ENV
```
# Set it if you're using external PocketBase installation (default: http://localhost:8090)
# Example: PUBLIC_POCKETBASE_URL=https://grimoire.mydomain.com:8090
PUBLIC_POCKETBASE_URL=http://localhost:8090
# RECOMMENDED: Change this to your email
ROOT_ADMIN_EMAIL=admin@grimoire.localhost
# RECOMMENDED: Use a secure password. Can be later changed in PocketBase's admin panel
ROOT_ADMIN_PASSWORD=changeme
# Set this to your domain name (default: http://localhost:5173)
# Example: ORIGIN=grimoire.mydomain.com
ORIGIN=https://grimoire.example.me
# Set this to true if you're using HTTPS (default: false)
# Example: PUBLIC_HTTPS_ONLY=true
PUBLIC_HTTPS_ONLY=false
# Change to the port you want the app to listen on (default: 5173)
# Example: PORT=80
PORT=5173
# Set this to true if you want to disable public signups (default: false)
PUBLIC_SIGNUP_DISABLED=false
```

DOCKER-COMPOSE.YML
```
version: '3.7'
services:
  pocketbase:
    image: spectado/pocketbase:0.19.2
    container_name: grimoire-pocketbase
    restart: unless-stopped
    ports:
      - '8090:80'
    volumes:
      - ./pb_data:/pb_data
      - ./pb_migrations:/pb_migrations/
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    env_file: .env
  grimoire:
    image: goniszewski/grimoire:latest
    container_name: grimoire
    restart: unless-stopped
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '$PORT:$PORT'
    depends_on:
      - pocketbase
```

I think I've covered everything.  Thanks again!!
