### ISSUE TITLE
could not connect to pocketbase

### ISSUE THREAD

**Issue by kendofriendo** [goniszewski/grimoire#97]
![image](https://github.com/goniszewski/grimoire/assets/39413174/b15d0b61-a2ec-4b52-81e3-9bed41e535e8)
![image](https://github.com/goniszewski/grimoire/assets/39413174/4008aa85-65cc-4583-8aba-8d4248843c52)

**Comment by goniszewski** [comment]
Hello @kendofriendo! Is the root URL for Pocketbase instance available under the provided address? If so, please look at the response headers and Pocketbase logs - maybe there's some useful information for us.

**Comment by kendofriendo** [comment]
I don't use the root url for anything, but I assigned it to one of my other apps and it works fine.

response headers: 
![image](https://github.com/goniszewski/grimoire/assets/39413174/c37198fc-6138-45ef-bd5e-eed65d3890a4)

pocketbase logs:
![image](https://github.com/goniszewski/grimoire/assets/39413174/4c72491d-bab0-4c21-8050-36d8e245f12f)

**Comment by kendofriendo** [comment]
In case it's relevant, the server running caddy is separate from the computer running grimoire. I have it connected via wireguard.

**Comment by goniszewski** [comment]
Is this problem still persisting for you while using https://github.com/goniszewski/grimoire/releases/tag/v0.3.5?

**Comment by kendofriendo** [comment]
Yes.

**Comment by saschatrebbin** [comment]
I have a similar, if not the same, problem - on v0.3.5.
And honestly I don't really know where to look for more information to debug this.

I deployed the app as shown  in the "Quick Start" of the docs, but changed the stack so no ports were directly opened.
instead I directed my reverse proxy to make the app and the pocketbase instance available by two separate domains.
The domain of the pocketbase instance is used as the value of PUBLIC_POCKETBASE_URL.

This is the content of my .env file

```
# Set it if you're using external PocketBase installation (default: http://pocketbase)
# Example: PUBLIC_POCKETBASE_URL=https://grimoire.mydomain.com:8090
PUBLIC_POCKETBASE_URL=https://grimoire-pocketbase.apps.hivenet.xyz
POCKETBASE_URL=https://grimoire-pocketbase.apps.hivenet.xyz
# RECOMMENDED: Change this to your email
ROOT_ADMIN_EMAIL=admin@grimoire.localhost
# RECOMMENDED: Use a secure password. Can be later changed in PocketBase's admin panel
ROOT_ADMIN_PASSWORD=changeme
# Set this to your domain name (default: http://localhost:5173)
# Example: PUBLIC_ORIGIN=grimoire.mydomain.com
PUBLIC_ORIGIN=grimoire.apps.hivenet.xyz
# Set this to true if you're using HTTPS (default: false)
# Example: PUBLIC_HTTPS_ONLY=true
PUBLIC_HTTPS_ONLY=true
# Change to the port you want the app to listen on (default: 5173)
# Example: PORT=80
PORT=5173
# Set this to true if you want to disable public signups (default: false)
PUBLIC_SIGNUP_DISABLED=false
```

and this is my docker-compose.yml:
```
---
services:
  pocketbase:
    image: spectado/pocketbase:0.22.10
    container_name: grimoire-pocketbase
    restart: unless-stopped
    #    ports:
    #  - '8090:80'
    volumes:
      - pb_data:/pb_data
      - pb_migrations:/pb_migrations/
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    env_file: .env
    depends_on:
      - grimoire
  grimoire:
    image: goniszewski/grimoire:latest
    container_name: grimoire
    restart: unless-stopped
    env_file: .env
    volumes:
      - pb_migrations:/app/pb_migrations/
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:$PORT/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
      #ports:
      #- '$PORT:$PORT'
volumes:
  pb_data:
  pb_migrations:

```

According to the log of my grimoire container the POCKETBASE_URL is http://localhost:8090 - a value I never specified.
If I attach to the grimoire container, open a shell and view the environment variables, the correct domain is shown.

This is a screenshot of the container logs:
![ksnip_20240522-211953](https://github.com/goniszewski/grimoire/assets/32403283/a352c6bf-b620-4f0a-97a5-4c03f0b14620)

And here is a screenshot of the env of a shell inside the grimoire container:
![ksnip_20240522-214040](https://github.com/goniszewski/grimoire/assets/32403283/f51d485a-77fb-4fd5-9c3c-03ecc68fa3cf)

If I hunted down those lines correctly, then that POCKETBASE_URL http://localhost:8090 is set here:
https://github.com/goniszewski/grimoire/blob/d1aaaae34fbaa432e2488f8500ad0b3f383830c0/src/lib/config.ts#L11

And if I understand the code correctly, then that value should only be used, when the system is started in dev-mode - which it is not (also shown in the screenshot above).

But on the screenshot above the log also shows a recurring app error, which **does** show my specified URL.
So let's ignore that POCKETBASE_URL variable for now and let's investigate the errors in the log

---

And here I get stuck, because I don't understand enough about Typescript or this app.
Let's look again at the error in the log:
![ksnip_20240522-211953](https://github.com/goniszewski/grimoire/assets/32403283/a352c6bf-b620-4f0a-97a5-4c03f0b14620)

This path in the error looks like the URL for the grimoire app/container - and if I understand correctly, then the /internal/pb/ path is meant for proxying pocketbase connections through internal endpoints.
**So why is a slash in front of that domain path?**

If I open the Browser DevTools in the webapp, I get the following:
![ksnip_20240522-212955](https://github.com/goniszewski/grimoire/assets/32403283/6cb4d889-6ecb-4420-bbe9-1352daeec705)

The error notification popping up shows the correct URL, but the DevTools reveal that the grimoire app URL is doubled in the sent XHR request.
I guess that is the cause of this issue, but I don't know how to proceed - I am not a dev and I'm absolutely not well versed in web app development.
